# SITE SETTINGS
title: "Dorien Huijser"

slogan: "Dorien Huijser's personal website"

description: "Everything you always wanted to know about Dorien's professional journey."

credits: '<p>Created with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on the <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a> theme.</p>'

author: Dorien
url: 'https://dorienhuijser.github.io'
baseurl: ''

improve_content: https://github.com/dorienhuijser/dorienhuijser.github.io/
urlimg: 'https://dorienhuijser.github.io/images/' # Example: <img src="{{ site.urlimg }}{{ post.image.title }}" /> Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)

logo: "logo.png" # size is 600x80 pixels

# Plugins
plugins:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate



# PAGINATION
paginate: 5 # Paginates all X entries
paginate_path: "blog/page:num" # Pagination path › Important for blog page in /blog/ to work



markdown           : kramdown # Theme works best, using toc function
permalink          : /:categories/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']

# Exclude files from production _site
exclude:
    - .sass-cache
        - Gemfile
        - Gemfile.lock
        - LICENSE
        - README.md
        - INSTALL.md
        - vendor



language: 'en'


# Use default.html front-matter and compress.html, see http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]



# DEFAULT SETTINGS

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: Dorien     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: Dorien     # Default author for posts





# NAVIGATION: _data/navigation.yml



#   Favicons, Chrome, Android & Apple Touch Buttons, https://mathiasbynens.be/notes/touch-icons
favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'



# SOCIAL MEDIA  _data/socialmedia.yml to adjust the left and right topbar navigation

socialmedia:
    twitter: DorienHuijser

# DISQUS, _includes/comments

#disqus_shortname: feelingresponsive

#    SASS, http://sass-lang.com/, http://jekyllrb.com/docs/assets/#sassscss
sass:
    sass_dir : _sass
    style    : :compressed



# Asciidoctor , https://github.com/asciidoctor/jekyll-asciidoc

asciidoctor-enabled: false
asciidoctor:
  description: 
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font

