# WORK EXPERIENCE
jobs:
  - jobtitle: "Data steward"
    joblinkname: "datasteward"
    jobtime: "2021-current"
    joblocation: "Utrecht University Library, Utrecht University, Utrecht, The Netherlands"
    jobinfo: ~
    jobdescription: {
      ? "Job description"
      : "As a data steward, I will help researchers in different research groups with their
      data management and open data-related problems and questions. Moreover, I will collaborate
      on a large project that aims to make handling privacy-sensitive data easier for researchers",
      }

  - jobtitle: "Lab and data manager"
    joblinkname: "labdatamanager"
    jobtime: "2020-2021"
    joblocation: "Society, Youth and Neuroscience Connected (<a href='https://erasmus-synclab.nl/' target='_blank'>SYNC</a>) lab, Erasmus University Rotterdam, Rotterdam, The Netherlands"
    jobinfo: ~
    jobdescription: {
      ? "Job description"
      : "<ul>
      <li>As <b>data manager</b>, I formulated ways to move towards <strong>open science practices</strong> and looked at how the group handled their research data (privacy, data structure, long-term access, etc.) 
      and how we could improve that. In both data management and open science, I tried to educate myself as much as possible and keep a close eye on international developments, connecting with researchers and 
      support staff from national and international institutions.</li>
      <li>As <b>lab manager</b>, I coordinated and supported all kinds of lab-wide events and initiatives, including (but not limited to):<ul>
      <li>organizing meetings</li>
      <li>functioning as liaison between the SYNC lab and EUR's research support staff</li>
      <li>improving how we worked (incl. with data)</li>
      <li>involvement in the citizen science platform, <a href='https://youngxperts.nl' target='_blank'>YoungXperts</a>, where youth are actively involved in the group's research during brainstorms and cocreation sessions</li>
      </ul></li></ul>",
      }

  - jobtitle: "Data manager"
    joblinkname: "datamanagerSU"
    jobtime: "2020-2021"
    joblocation: "Leiden Consortium on Individual Development 
    (<a href='https://www.universiteitleiden.nl/en/research/research-projects/social-and-behavioural-sciences/leiden-consortium-on-individual-development-l-cid' target='_blank'>L-CID</a>), 
    Leiden University, Leiden, The Netherlands"
    jobinfo: ~
    jobdescription: {
      ? "Job description"
      : "As data manager for L-CID, a large multi-cohort twin study, I helped make the data and metadata 
      <a href='https://www.go-fair.org/fair-principles/' target='_blank'>FAIR</a> and their documentation interpretable, in order for this amazing dataset to be useful and useable in the future.",
    }

  - jobtitle: "Data manager"
    joblinkname: "datamanagerBD"
    jobtime: "2019-2020"
    joblocation: "<a href='https://brainanddevelopment.nl/' target='_blank'>Brain and Development Research Center</a>, Leiden University, Leiden, The Netherlands"
    jobinfo: ~
    jobdescription: {
      ? "Job description"
      : "In this developmental psychology group, I helped researchers transition towards applying better data management and open research practices, such as folder structures and versioning, 
    preregistration, data sharing and privacy issues. I continued this job when the Research Center was split up into the <a href='https://erasmus-synclab.nl' target='_blank'>SYNC lab</a> and the 
    <a href='https://changeleiden.nl' target='_blank'>CHANGE Leiden</a> research platform.",
    }

  - jobtitle: "Educational content developer and e-moderator"
    joblinkname: "contentdeveloper"
    jobtime: "2019-2020"
    joblocation: "<a href='https://www.umcutrecht.nl/en/educational-expertise' target='_blank'>Utrecht University Medical Center</a> and 
    <a href='https://www.ivd-utrecht.nl/en' target='_blank'>Animal Welfare Body</a>, Utrecht, The Netherlands"
    jobinfo: ~
    jobdescription: {
      ? "Job description"
      : "In the development and testing phase of the learning track 
    <a href='https://www.uu.nl/en/events/my-animal-research-experimental-design-fully-booked' target='_blank'><i>My Animal Research: Experimental Design</i></a>, a learning track for PhD students 
    who are setting up an animal experiment, I developed the contents of the online learning environment and functioned as e-moderator during the pilot phase of the project (Sept.-Dec. 2019), 
    keeping contact with all involved participants, teachers and coordinators.",
    }

  - jobtitle: "Several side jobs"
    joblinkname: "sidejobs"
    jobtime: "2010-2019"
    joblocation: ~
    jobinfo: "During my secondary school and university studies, I had several side jobs"
    jobdescription: {
      ? "List of jobs"
      : "<ul>
    <li>2016-2019: Tutor for several secondary school pupils in several subjects (e.g, maths, chemistry, Latin, Greek)</li>
    <li>2018-2019: Student assistant on the <a href='https://juniorhersenen.nl/onderzoeken/brainlinks/' target='_blank'>Brainlinks</a> project at the 
    <a href='https://brainanddevelopment.nl/' target='_blank'>Brain and Development Research Center</a>, Leiden University</li>
    <li>2016: <a href='https://www.studiekring.nl/samenwerken/zomerschool' target='_blank'>Summer school</a> tutor (maths and Latin): pupils had the chance to 
    still go to the next year if they passed a test after two weeks of additional study in the summer</li>
    <li>2014-2016: Sales employee at <a href='https://www.blokker.nl/' target='_blank'>Blokker</a>, Utrecht</li>
    <li>2012-2013: Cashier at <a href='https://www.jumbo.com/' target='_blank'>Jumbo</a> supermarket, Leeuwarden</li>
    </ul>",
    }

# EDUCATION
educations:
  - educationtitle: "Online courses"
    educationlinkname: "onlinecourses"
    educationtime: "2016-2021"
    educationlocation: ~
    educationinfo: "To gain some more relevant skills, I somtimes follow online courses, most of them in my free time"
    educationdescription: {
      ? "List of courses"
      : "<ul>
          <li>2021: Introduction to programming in Python - <i>Center for Digital Scholarship, Leiden University</i>, see the <a href='https://cdsleiden.github.io/python-tutorial/Welcome.html' target='_blank'>materials here</a></li>
          <li>2019-2020: Specialization Data Science: Foundations using R - <i>Johns Hopkins University via <a href='https://www.coursera.org/specializations/data-science-foundations-r' target='_blank'>Coursera</a></i></li>
          <li>2019: Research data management and sharing (grade: 89.7%) - <i>UNC & University of Edinburgh via <a href='https://www.coursera.org/learn/data-management' target='_blank'>Coursera</a></i></li>
          <li>2019: Adobe InDesign Made Easy: A Beginners Guide to InDesign - <i>Infinite Skills via <a href='https://www.udemy.com/course/adobe-indesign-made-easy/' target='_blank'>Udemy</a></i></li>
          <li>2016: Several statistics courses (average grade: 92.6%): Basic statistics, Inferential statistics, quantitative methods - <i>University of Amsterdam via 
          <a href='https://www.coursera.org/specializations/social-science' target='_blank'>Coursera</a></i></li>
        </ul>"
    }

  - educationtitle: "MSc <a href='https://www.uu.nl/masters/en/neuroscience-and-cognition/study-programme' target='_blank'>Neuroscience and Cognition</a> (8.5)"
    educationlinkname: "neuroscience"
    educationtime: "2016-2019"
    educationlocation: "Utrecht University, Utrecht, The Netherlands"
    educationinfo: "Major: Cognitive neuroscience <br> Minor: <a href='https://studyguidelifesciences.nl/profiles/communication-profile' target='_blank'>Science education and communication</a>"
    educationdescription: {
      ? "Activities"
      : "<ul>
        <li>2018-2019: Intern education - <i><a href='https://umu.nl/' target='_blank'>Utrecht University Museum</a>, Utrecht</i><br> As part of my minor Science education and communication, 
        I developed an <a href='https://umu.nl/onderwijs/vo/wetenschapsworkshop-aandacht-havo-vwo/' target='_blank'>educational program</a> for the University Museum Utrecht for secondary school pupils 
        (havo/vwo 1-2 and vmbo 1-3) about social sciences (attention), using the methods of inquiry-based learning (onderzoekend leren)</li>
        <li>2018: Literature research: 'Neural mechanisms of adolescent fear extinction and fear extinction during reconsolidation: a literature review', supervised by dr. Marieke Bos and prof. dr. Joke Baas.</li>
        <li>2017-2018: Research intern - <i><a href='https://brainanddevelopment.nl/' target='_blank'>Brain and Development Research Center</a>, Leiden University, Leiden</i><br>During this internship, 
        I set up, carried out and wrote about an fMRI study and planned and tested many adolescents (9-17 years old) for a large longitudinal research project (<a href='https://juniorhersenen.nl/onderzoeken/brainlinks/' target='_blank'>Brainlinks</a>)</li>
        <li>2017-2018: Author (<a href='http://journal.neuroscience-cognition.org/archive/19' target='_blank'>2017: 11(1)</a>) and reviewer 
        (<a href='http://journal.neuroscience-cognition.org/archive' target='_blank'>2017: 11(1-2) & 2018: 12(1-2)</a>) at the Journal of Neuroscience and Cognition</li>
        <li>2016-2017: Secretary - <i><a href='https://www.mindthebrain.nl/' target='_blank'>Mind the Brain</a> symposium, Utrecht University, Utrecht</i><br>With 8 students, we organized a two-day 
        neuroscience symposium, themed 'Criminal Minds'</li>
        <li>2016-2017: Research intern - <i><a href='https://www.uu.nl/medewerkers/organogram/FSW/54/269' target='_blank'>Experimental Psychology</a>, Utrecht University, Utrecht</i><br>
        During this project, I set up, carried out and wrote about a longitudinal experiment into unilateral hearing loss and sound localization among healthy adults</li>
        </ul>",
      ? "Theses and reports"
      : "<ul>
      <li>Huijser, D.C. (2018). Neural mechanisms of adolescent fear extinction and fear extinction during reconsolidation: a literature review. 
      <i>Master thesis</i>, <a href='https://dspace.library.uu.nl/handle/1874/401338' target='_blank'>link to thesis</a>.</li>
      <li>Huijser, D.C. (2018). Tapping Trust Task (TTT): Investigating the mechanisms of interpersonal synchrony in the trust game. <i>Internship report</i>, 
      <a href='http://dspace.library.uu.nl/handle/1874/401911' target='_blank'>link to report</a>.</li>
      <li>Huijser, D.C. (2017). Using audiovisual recalibration to restore spatial hearing in the human brainstem during asymmetrical hearing loss. <i>Internship report</i>. Embargoed.</li>
      <li>Huijser, D.C. (2017). Functional connectivity changes and cognitive deficits in Alzheimer’s Disease. <i>Journal of Neuroscience and Cognition</i>, 
      <a href='http://journal.neuroscience-cognition.org/archive/19' target='_blank'><i>11</i>(1)</a>, <a href='https://doi.org/10.31237/osf.io/853a7' target='_blank'>link to review</a>.</li>
      </ul>",
    }

  - educationtitle: "BSc <a href='https://www.uu.nl/bachelors/liberal-arts-and-sciences' target='_blank'>Liberal Arts and Sciences</a> (8.2)"
    educationlinkname: "las"
    educationtime: "2013-2016"
    educationlocation: "Utrecht University, Utrecht, The Netherlands"
    educationinfo: "Major: Cognitive and neurobiological psychology <br> Minor: <a href='https://students.uu.nl/gw/taalontwikkeling' target='_blank'>Language development</a>"
    educationdescription: {
      ? "Theses"
      : "<ul>
      <li>Huijser, D.C., & Lichtenberg, L. (2016). Social Status and Status Motivations: The Association between the Wish for Popularity and Social Status in Late Childhood. Bachelor thesis, 
      <a href='http://dspace.library.uu.nl/handle/1874/338248' target='_blank'>http://dspace.library.uu.nl/handle/1874/338248</a><br>Thesis supervised by dr. Aart Franken, grade: 8.0/10</li>
      <li>Huijser, D.C., Bakermans, M., Purkins, M. (2015). Looking down, moving up. An interdisciplinary approach to the consequences of the current language situation that has developed as a result of 
      the elite status of the English language in India. Interdisciplinary bachelor thesis, <a href='http://dspace.library.uu.nl/handle/1874/340072' target='_blank'>http://dspace.library.uu.nl/handle/1874/340072</a><br>
      Thesis supervised by dr. Merel van Goch, grade: 7.9/10</li></ul>"
    }

  - educationtitle: "Voorbereidend Wetenschappelijk Onderwijs (VWO) (8.1)"
    educationlinkname: "cgbn"
    educationtime: "2007-2013"
    educationlocation: "<a href='https://www.cgbn.nl/' target='_blank'>Christelijk Gymnasium Beyers Naudé</a>, Leeuwarden,The Netherlands"
    educationinfo: "Profile: Economics and Society"
    educationdescription: ~

# SKILLS
skills:
  - skillcategory: "Languages"
    skilllinkname: "languages"
    skilldescription: ~
    skilllist: "<ul>
    <li>⭐⭐⭐⭐⭐ 🇳🇱 Dutch (native)</li>
    <li>⭐⭐⭐⭐ 🇬🇧 English (competent in writing, understanding, speaking)</li>
    <li>⭐⭐ 🇫🇷 French, 🇩🇪 German, ❤️ Frisian (basic)</li></ul>"

  - skillcategory: "Software"
    skilllinkname: "software"
    skilldescription: ~
    skilllist: "<ul>
        <li>⭐⭐⭐⭐ Microsoft Office and Google alternatives</li>
        <li>⭐⭐⭐⭐ (Interactive) presentation tools</li>
        <li>⭐⭐⭐Markdown</li>
        <li>⭐⭐⭐Git(hub)</li>
        <li>⭐⭐HTML</li>
        <li>⭐R</li>
        <li>⭐Adobe InDesign</li>
        <li>⭐Matlab</li>
        <li>⭐SPSS</li></ul>"

  - skillcategory: "Competences"
    skilllinkname: "competences"
    skilldescription: "Please also see the <a href='/testimonials' target='_blank'>Testimonial page</a>"
    skilllist: "<ul>
    <li>Organization</li>
    <li>Analytical</li>
    <li>Collaborative</li>
    <li>Goal-oriented</li>
    <li>Eager to learn</li>
    <li>Communicative</li></ul>"