project:
  type: website
  output-dir: "../docs"
  resources:
    - CNAME

website:
  title: "Dorien Huijser"
  site-url: https://www.dorienhuijser.com/
  description: "Dorien Huijser's website"
  page-footer:
    border: true
    background: light
    center: "Website created with <i class='bi bi-suit-heart-fill'></i>, [<i class='bi bi-github'></i>](https://github.com/dorienhuijser/dorienhuijser.github.io) and [Quarto](https://quarto.org/)."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: What I do
      - href: blog.qmd
        text: Blog
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
      - icon: rss
        href: blog.xml
format:
  html:
    theme:
    - journal
    - assets/styles.scss
    toc: true



