---
title: "What the hack? Bringing about a practical tool through open collaboration"
description: "A draft post to list things I don't want to lose but also don't want to publish."
author: "Dorien Huijser"
date: today
draft: true
---

### In the media

- 2023-11-05: Spotlight on Dorien Huijser (tDCC self-interview): <https://tdcc.nl/spotlight-on-dorien-huijser/>
- 2021-06-14: Interview Leiden University: <https://www.universiteitleiden.nl/en/news/2021/06/psychology-lab-embraces-open-science>

### CV (old)

**Work experience**

- Research data manager @ Utrecht University Library, Utrecht University, Utrecht, The Netherlands
   - 2021-current
   - As a research data manager, I support researchers at the university with their data management and open data-related issues. Typical topics include data storage, privacy, metadata, making data and software FAIR, reproducibility, version control, etc.
- Lab and data manager @  Society, Youth and Neuroscience Connected ([SYNC lab](https://erasmus-synclab.nl/), Erasmus University Rotterdam, Rotterdam, The Netherlands
   - 2020-2021
   - As **data manager**, I formulated ways to move towards open science practices and looked at how the group handled their research data (privacy, data structure, long-term access, etc.) and how we could improve that. In both data management and open science, I tried to educate myself as much as possible and keep a close eye on international developments, connecting with researchers and support staff from national and international institutions. As **lab manager**, I coordinated and supported all kinds of lab-wide events and initiatives, including (but not limited to): organizing meetings, functioning as liaison between the SYNC lab and EUR's research support staff, improving how we worked (incl. with data), involvement in the citizen science platform [YoungXperts](https://youngxperts.nl), where youth are actively involved in the group's research during brainstorms and cocreation sessions
- Data manager @ Leiden Consortium on Individual Development ([L-CID](https://www.universiteitleiden.nl/en/research/research-projects/social-and-behavioural-sciences/leiden-consortium-on-individual-development-l-cid)), Leiden University, Leiden, The Netherlands
   - 2020-2021
   - As data manager for L-CID, a large multi-cohort twin study, I helped make the data and metadata [FAIR](https://www.go-fair.org/fair-principles/) and their documentation interpretable, in order for this amazing dataset to be useful and useable in the future.
- Data manager @ [Brain and Development Research Center](https://brainanddevelopment.nl/), Leiden University, Leiden, The Netherlands
   - 2019-2020
   - In this developmental psychology group, I helped researchers transition towards applying better data management and open research practices, such as folder structures and versioning, preregistration, data sharing and privacy issues. I continued this job when the Research Center was split up into the [SYNC lab](https://erasmus-synclab.nl) and the [CHANGE Leiden](https://changeleiden.nl) research platform.
- Educational content developer and e-moderator @ [Utrecht University Medical Center](https://www.umcutrecht.nl/en/educational-expertise) and [Animal Welfare Body Utrecht](https://www.ivd-utrecht.nl/en), Utrecht, The Netherlands
   - 2019-2020
   - In the development and testing phase of the learning track [My Animal Research: Experimental Design](https://www.uu.nl/en/events/my-animal-research-experimental-design-fully-booked), a learning track for PhD students who are setting up an animal experiment, I developed the contents of the online learning environment and functioned as e-moderator during the pilot phase of the project (Sept.-Dec. 2019), keeping contact with all involved participants, teachers and coordinators.
- Several side jobs
   - 2010-2019
   - During my secondary school and university studies, I had several side jobs:
      - 2016-2019: Tutor for several secondary school pupils in several subjects (e.g, maths, chemistry, Latin, Greek)
      - 2018-2019: Student assistant on the [Brainlinks](https://juniorhersenen.nl/onderzoeken/brainlinks/) project at the [Brain and Development Research Center](https://brainanddevelopment.nl/), Leiden University
      - 2016: [Summer school](https://www.studiekring.nl/samenwerken/zomerschool) tutor (maths and Latin): pupils had the chance to still go to the next year if they passed a test after two weeks of additional study in the summer
      - 2014-2016: Sales employee at [Blokker](https://www.blokker.nl/), Utrecht
      - 2012-2013: Cashier at [Jumbo](https://www.jumbo.com/) supermarket, Leeuwarden

**Education**

- Online courses
   - 2016-2021
   - To gain some more relevant skills, I sometimes follow online courses, most of them in my free time:
      - 2021: Introduction to programming in Python @ Center for Digital Scholarship, Leiden University, see the [materials here](https://cdsleiden.github.io/python-tutorial/Welcome.html)
      - 2019-2020: Specialization Data Science: Foundations using R @ Johns Hopkins University via [Coursera](https://www.coursera.org/specializations/data-science-foundations-r)
      - 2019: Research data management and sharing (grade: 89.7%) @ UNC & University of Edinburgh via [Coursera](https://www.coursera.org/learn/data-management)
      - 2019: Adobe InDesign Made Easy: A Beginners Guide to InDesign @ Infinite Skills via [Udemy](https://www.udemy.com/course/adobe-indesign-made-easy/)
      - 2016: Several statistics courses (average grade: 92.6%): Basic statistics, Inferential statistics, quantitative methods @ University of Amsterdam via [Coursera](https://www.coursera.org/specializations/social-science)

- MSc [Neuroscience and Cognition](https://www.uu.nl/masters/en/neuroscience-and-cognition/study-programme) (8.5)
   - 2016-2019
   - Utrecht University, Utrecht, The Netherlands
   - Major: Cognitive neuroscience, Minor: [Science Education and Communication](https://studyguidelifesciences.nl/profiles/communication-profile)
   - Activities:
      - 2018-2019: Intern education @ [Utrecht University Museum](https://umu.nl/), Utrecht. As part of my minor Science education and communication, I developed an [educational program](https://umu.nl/onderwijs/vo/wetenschapsworkshop-aandacht-havo-vwo/) for the University Museum Utrecht for secondary school pupils (havo/vwo 1-2 and vmbo 1-3) about social sciences (attention), using the methods of inquiry-based learning (onderzoekend leren)
      - 2018: Literature research: 'Neural mechanisms of adolescent fear extinction and fear extinction during reconsolidation: a literature review', supervised by dr. Marieke Bos and prof. dr. Joke Baas.
      - 2017-2018: Research intern @ [Brain and Development Research Center](https://brainanddevelopment.nl/), Leiden University, Leiden. During this internship, I set up, carried out and wrote about an fMRI study and planned and tested many adolescents (9-17 years old) for a large longitudinal research project ([Brainlinks](https://juniorhersenen.nl/onderzoeken/brainlinks/))
      - 2017-2018: Author ([2017: 11(1)](http://journal.neuroscience-cognition.org/archive/19)) and reviewer ([2017: 11(1-2) & 2018: 12(1-2)](http://journal.neuroscience-cognition.org/archive)) at the Journal of Neuroscience and Cognition
      - 2016-2017: Secretary @ [Mind the Brain symposium](https://www.mindthebrain.nl/), Utrecht University, Utrecht. With 8 students, we organized a two-day neuroscience symposium, themed 'Criminal Minds'
      - 2016-2017: Research intern @ [Experimental Psychology](https://www.uu.nl/medewerkers/organogram/FSW/54/269), Utrecht University, Utrecht. During this project, I set up, carried out and wrote about a longitudinal experiment into unilateral hearing loss and sound localization among healthy adults
   - Theses and reports:
      - Master thesis: Huijser, D.C. (2018). Neural mechanisms of adolescent fear extinction and fear extinction during reconsolidation: a literature review. <https://dspace.library.uu.nl/handle/1874/401338>
      - Internship report: Huijser, D.C. (2018). Tapping Trust Task (TTT): Investigating the mechanisms of interpersonal synchrony in the trust game. <http://dspace.library.uu.nl/handle/1874/401911>
      - Internship report: Huijser, D.C. (2017). Using audiovisual recalibration to restore spatial hearing in the human brainstem during asymmetrical hearing loss. Embargoed.
      - Huijser, D.C. (2017). Functional connectivity changes and cognitive deficits in Alzheimer’s Disease. Journal of Neuroscience and Cognition, [11(1)](http://journal.neuroscience-cognition.org/archive/19), <https://doi.org/10.31237/osf.io/853a7> 

- BSc [Liberal Arts and Sciences](https://www.uu.nl/bachelors/liberal-arts-and-sciences) (8.2)
   - 2013-2016
   - Utrecht University, Utrecht, The Netherlands
   - Major: Cognitive and neurobiological psychology. Minor: [Language development](https://students.uu.nl/gw/taalontwikkeling)
   - Theses:
      - Huijser, D.C., & Lichtenberg, L. (2016). Social Status and Status Motivations: The Association between the Wish for Popularity and Social Status in Late Childhood. Bachelor thesis, <http://dspace.library.uu.nl/handle/1874/338248>. Thesis supervised by dr. Aart Franken, grade: 8.0/10
      - Huijser, D.C., Bakermans, M., Purkins, M. (2015). Looking down, moving up. An interdisciplinary approach to the consequences of the current language situation that has developed as a result of the elite status of the English language in India.  Interdisciplinary bachelor thesis, <http://dspace.library.uu.nl/handle/1874/340072>. Thesis supervised by dr. Merel van Goch, grade: 7.9/10

- Voorbereidend Wetenschappelijk Onderwijs (VWO) (8.1)
   - 2007-2013
   - [Christelijk Gymnasium Beyers Naude](https://www.cgbn.nl/), Leeuwarden,The Netherlands
   - Profile: Economics and Society

**Skills**

- Languages: Dutch (native), English (competent in writing, understanding, speaking), French (basic), German (basic), Frisian (basic)
- Software: Microsoft Office and Google alternatives, (interactive) presentation tools, Markdown, Git(hub), HTML, R, SPSS
- Competences: Organization, analytical, collaborative, goal-oriented, eager to learn, communicative

### Testimonials

Answer garden:

<iframe src="https://answergarden.ch/embed/1547073" width="640px" height="400px" style="border: none;" scrolling="no" frameborder="0" title="AnswerGarden" allowTransparency="true"><p><a href="https://answergarden.ch/1547073">Go to AnswerGarden</a></p></iframe>


<iframe src="https://answergarden.ch/embed/1670175" width="640px" height="400px" style="border: none;" scrolling="no" frameborder="0" title="AnswerGarden" allowTransparency="true"><p><a href="https://answergarden.ch/1670175">Go to AnswerGarden</a></p></iframe>


Testimonials in text:

> Dorien is a great team player with good communication skills. We were both part of a committee to organize a two-day symposium. Dorien always had her work in order, communicated well with the rest of the team and helped others where necessary. During her studies, she has proven herself to have strong analytical skills and a great work attitude. She's a winner!
> Friend and fellow student

> Dorien has been a valuable addition to the team, both in terms of her personal strengths and knowledge in RDM. Her strengths include being organized, reliable, efficient, prompt. Generally, this allows her maintain a healthy pace and momentum in her tasks and projects. While Dorien works well independently, she is also a good team-player: she’s pleasant and good-natured, she cooperates and collaborates well, she actively communicates/participates with the team, she gets involved and contributes where she can/helps out if needed.
> Colleague

> Dorien knows to find her way quickly in complex material, and collaborates well with different specialists. In the Data Privacy Project, she shows to be a great project manager, who is approachable and communicates in a nice way.
> Colleague

> If something needs arranging, Dorien is going to tackle things hands-on immediately.
> Friend
