---
title: "Data stewardship professionalization"
description: "A national project to provide training and community resources for data professionals"
image: "https://researchdata.nl/wp-content/uploads/2025/04/RDNL_Logo_RGB.svg"
image-alt: "Logo of Research Data Netherlands (RDNL)"
---

Since 2025, I have joined the Open Science NL-funded project "[National training and community platform for research data professionals](https://researchdata.nl/en/national-training-and-community-platform-for-research-data-professionals/)" which runs from 2025 until 2028 within the Research Data Netherlands consortium, consisting of 4TU.ResearchData, DANS-KNAW, SURF and Health-RI.

This project consists of four work packages:

- WP1: Project communication and coordination
- WP2: 
  - Developing a data steward curriculum and providing certification
  - Developing new data steward training
  - Teaching RDNL courses "Essentials 4 Data Support" and "GDPR 4 Data Support"
  - Developing train-the-trainer materials
  - Implementing a feedback loop
- WP3: Delivery of the platform
- WP4: Sustainability and governance of the platform

At the moment, my involvement is primarily in WP 2.
In March 2026, we delivered a [first version of the national curriculum](https://doi.org/10.5281/zenodo.17952685) (see also the [blog about the curriculum](https://researchdata.nl/en/2026/03/competency-to-capability-from-curriculum-to-training-programme-for-data-professionals/)).
Feel free to check out the [project proposal](https://doi.org/10.5281/zenodo.17952713) or get in toch with me about this project.
